using AutoMapper;
using portal.DTOs;
using portal.Models;

namespace portal.Mappings;
public class CareerPathInfoProfile : Profile
{
    public CareerPathInfoProfile()
    {
        // ---------- Entity <-> Read DTO ---------- //
        CreateMap<CareerPathInfo, CareerPathInfoDTO>().ReverseMap();

        // ---------- Create DTO -> Entity ---------- //
        CreateMap<CreateCareerPathInfoDTO, CareerPathInfo>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // ID generated by DB
            .ForMember(dest => dest.Employee, opt => opt.Ignore()); // prevent circular refs

        // ---------- Update DTO -> Entity ---------- //
        CreateMap<UpdateCareerPathInfoDTO, CareerPathInfo>()
            .ForAllMembers(opt => opt.Condition((src, dest, srcMember) => srcMember != null)); // only map non-null
    }
}

